### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by warren8r** [LukeTillman/cassandra-ssis#1]
Hello,
I am interested in pulling data from Cassandra to SQL Server using SSIS - can you explain how this works?  Is this working?

Thank you for your time!

Matt

**Comment by LukeTillman** [comment]
Hey Matt,

This is a project I started on a while back but haven't gotten back around to in a bit. There isn't anything currently working. Back when I started working on it, I didn't see anyone else offering a Cassandra - SSIS connector, but that may have changed in the last number of months. Good luck!

-L-

**Comment by warren8r** [comment]
Thank you for getting back to me, Luke. Really appreciate it!

Matt
